// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsZWHi-lqHtqQ5lWEKtkpPIypawEcP4HA',
    appId: '1:902409286318:web:517da4ed162221222c733f',
    messagingSenderId: '902409286318',
    projectId: 'task-7cef3',
    authDomain: 'task-7cef3.firebaseapp.com',
    storageBucket: 'task-7cef3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeCAVjmlC11_cRg4eyVycGBCmgkXP7550',
    appId: '1:902409286318:android:5504a7da3460bb462c733f',
    messagingSenderId: '902409286318',
    projectId: 'task-7cef3',
    storageBucket: 'task-7cef3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMIY_c52LlQMX_fX3-7aN4ZYk0yZIehhA',
    appId: '1:902409286318:ios:a8aeeac3772690222c733f',
    messagingSenderId: '902409286318',
    projectId: 'task-7cef3',
    storageBucket: 'task-7cef3.appspot.com',
    iosBundleId: 'com.example.taskFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMIY_c52LlQMX_fX3-7aN4ZYk0yZIehhA',
    appId: '1:902409286318:ios:d675702946b9985d2c733f',
    messagingSenderId: '902409286318',
    projectId: 'task-7cef3',
    storageBucket: 'task-7cef3.appspot.com',
    iosBundleId: 'com.example.taskFirebase.RunnerTests',
  );
}
